##
 # This file is part of the Scr.be Website
 #
 # (c) Scribe Inc. <source@scribe.software>
 #
 # For the full copyright and license information, please view the LICENSE.md
 # file that was distributed with this source code.
 ##

src_dirs:
    - src
    - web

coverage_clover: build/phpunit/clover.xml
json_path: build/phpunit/coveralls-upload.json

# EOF
