language: php

branches:
    only:
        - master

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION="2.6.*"
        - php: 5.6
          env: SYMFONY_VERSION="2.7.*@dev"
        - php: nightly
          env: SYMFONY_VERSION="2.7.*@dev"
        - php: hhvm-nightly
          env: SYMFONY_VERSION="2.7.*@dev"
    allow_failures:
        - php: 5.6
          env: SYMFONY_VERSION="2.7.*@dev"
        - php: nightly
          env: SYMFONY_VERSION="2.7.*@dev"
        - php: hhvm-nightly
          env: SYMFONY_VERSION="2.7.*@dev"
    fast_finish: true

before_install:
    - mkdir -p build/logs
    - mkdir -p bin
    - composer install --dev --prefer-source

install:
    - travis_retry composer self-update
    - travis_retry composer clear-cache
    - if [ "${SYMFONY_VERSION}" == "2.6.*" ]; then travis_retry composer install --no-interaction; else travis_retry composer require symfony/symfony:${SYMFONY_VERSION} --no-interaction; fi

script:
    - bin/phpunit --verbose --configuration phpunit.travis.xml

after_script:
    - bin/coveralls -c .coveralls.yml -vvv
    - if [ "${SYMFONY_VERSION}" == "2.6.*" ]; then bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml; fi
