---

"general":

  "preferred_scheme" : "https"

"shortlinks":

  "aliases":
    "open"               : "open-source"

  "go":
    "scribe-home"        : "https://github.com/src-run/"
    "explore"            : "https://src.run/groups/php"
    "open-source"        : "https://src.run/explor"
    "shield-no-deps"     : "https://img.shields.io/badge/dependencies-none-44cc11.svg?style=flat-square"
    "twig-api"           : "http://twig.sensiolabs.org/api/master/index.html"
    "twig"               : "http://twig.sensiolabs.org/"
    "symfony-api"        : "http://api.symfony.com/"
    "symfony"            : "https://symfony.com/"
    "sami"               : "https://github.com/FriendsOfPHP/Sami"
    "rtd"                : "http://readthedocs.org/"
    "readme_welcome"     : "https://www.youtube.com/watch?v=a_FiuHOiJiY&t=1m1s"
    "readme_imagination" : "https://www.youtube.com/watch?v=r2pt2-F2j2g&t=24s"
    "fsf"                : "https://en.wikipedia.org/wiki/Free_Software_Foundation"
    "osi"                : "https://en.wikipedia.org/wiki/Open_Source_Initiative"
    "gpl"                : "https://en.wikipedia.org/wiki/GNU_General_Public_License"
    "mit"                : "https://en.wikipedia.org/wiki/MIT_License"

  "file":
    "get-build-knowledge.sh"            : "https://raw.githubusercontent.com/src-run/project-build-knowledge/aboriginal-pasta/build/env/get_build-knowledge.sh"
    "fetch-all-repos-gen-api-docs.bash" : "https://raw.githubusercontent.com/src-run/build-knowledge-shared/aboriginal-pasta/build/doc/fetch-all-repos-and-gen.sh"

"user_aliases":

  "robfrawley"    : "rmf"
  "dcorrigan"     : "dfc"
  "cchimi"        : "cmc"
  "andrewhthomas" : "aht"

"group_explanation":

  "wonka" :
    watch : "WtRwBzBFSmA&t=8s"
  "teavee" :
    watch : "peqzq3V2WAw&t=0m22s"
  "arthur" :
    watch : "7xU8_TSmPCY&t=0m5s"
  "augustus" :
    watch : "FdSORiSaRW8&t=1s"
  "vermicious" :
    search : "vermicious knids"

"redirects":

  "users":
    "services":

      "git":
        "alias" : "github"

      "github":
        "url"   : "//github.com/%user%"

      "lab":
        "alias" : "gitlab"

      "gitlab":
        "url"   : "//gitlab.com/u/%user%"
        "usermap" :
          "rmf" : "robfrawley"

      "time":
        "alias" : "wakatime"

      "wakatime":
        "url"   : "//wakatime.com/@%user%"

  "services":

    "group"                    : "//github.com/%org%?query=%search%"
    "group_explanation_video"  : "//www.youtube.com/watch?v=%video%"
    "group_explanation_search" : "//google.com/?q=%search%#safe=off&q=%search%"
    "github"                   : "//github.com/%org%/%bundle-name%/tree/%branch%"
    "github_issues"            : "//github.com/%org%/%bundle-name%/issues"
    "github_collaborators"     : "//github.com/%org%/%bundle-name%/graphs/contributors"
    "gitlab"                   : "//src.run/php/%bundle-name%"
    "gitlab_issues"            : "//src.run/php/%bundle-name%/issues"
    "contributing"             : "//github.com/%org%/%bundle-name%/blob/master/CONTRIBUTING.md"
    "readme"                   : "//github.com/%org%/%bundle-name%/blob/master/README.md"
    "readme_shield"            : "//img.shields.io/badge/docs-README-9933FF.svg?style=flat-square"
    "license"                  : "//github.com/%org%/%bundle-name%/blob/master/LICENSE.md"
    "license_shield"           : "//img.shields.io/badge/license-MIT-0066FF.svg?style=flat-square"
    "packagist"                : "//packagist.org/packages/%org%/%bundle-name%"
    "packagist_shield"         : "//img.shields.io/packagist/v/%org%/%bundle-name%.svg?style=flat-square"
    "packagist_v_shield"       : "//img.shields.io/packagist/v/%org%/%bundle-name%.svg?style=flat-square"
    "packagist_dm_shield"      : "//img.shields.io/packagist/dm/%org%/%bundle-name%.svg?style=flat-square"
    "packagist_dd_shield"      : "//img.shields.io/packagist/dd/%org%/%bundle-name%.svg?style=flat-square"
    "packagist_dt_shield"      : "//img.shields.io/packagist/dt/%org%/%bundle-name%.svg?style=flat-square"
    "packagist_pre_shield"     : "//img.shields.io/packagist/vpre/%org%/%bundle-name%.svg?style=flat-square"
    "rtd"                      : "//%bundle-name%.src.run"
    "docs"                     : "//%bundle-name%.src.run"
    "sami"                     : "//src.run/docs/%bundle-name%/api/master/index.html"
    "api"                      : "//src.run/docs/%bundle-name%/api/master/index.html"
    "api_shield"               : "//img.shields.io/badge/docs-API%20Reference-FF33CC.svg?style=flat-square"
    "coveralls"                : "//coveralls.io/r/%org%/%bundle-name%?branch=%branch%"
    "coveralls_shield"         : "//img.shields.io/coveralls/%org%/%bundle-name%/%branch%.svg?style=flat-square"
    "scrutinizer"              : "//scrutinizer-ci.com/g/%org%/%bundle-name%"
    "scrutinizer_shield"       : "//img.shields.io/scrutinizer/g/%org%/%bundle-name%/branch%.svg?style=flat-square"
    "gemnasium"                : "//gemnasium.com/%org%/%bundle-name%"
    "gemnasium_shield"         : "//img.shields.io/gemnasium/%org%/%bundle-name%.svg?style=flat-square"
    "codacy"                   : "//www.codacy.com/app/%org%/%bundle-name%"
    "codacy_shield"            : "//img.shields.io/codacy/%id%.svg?style=flat-square"
    "sensiolabs"               : "//insight.sensiolabs.com/projects/%sensiolabs-id%"
    "styleci"                  : "//styleci.io/repos/%id%"
    "styleci_shield"           : "//styleci.io/repos/%id%/shield"
    "travis_shield"            : "//img.shields.io/travis/%org%/%bundle-name%/%branch%.svg?style=flat-square"
    "travis_api_cc"            : "//api.travis-ci.org/repos/%org%/%bundle-name%/cc.xml"
    "travis":
      "public"                 : "//travis-ci.org/%org%/%bundle-name%"
      "private"                : "//magnum.travis-ci.com/%org%/%bundle-name%"

  "shields":
    "style"                : "flat-square"
    "branch"               : "master"

    "baseurl":
       "shields"           : "//img.shields.io/"
       "rtd"               : "//readthedocs.org/projects/"

    "services":
      "custom"             : "badge/%title%-%state%-%color%.svg"
      "packagist"          : "packagist/v/%packagist-name%.svg"
      "packagist_dev"      : "packagist/vpre/%packagist-name%.svg"
      "rtd"                : "%bundle-name%/badge/?version=latest&"
      "sami"               : "badge/docs-api%20reference-c75ec1.svg"
      "travis"             : "/travis/%org%/%bundle-name%/%branch%.svg"
      "coveralls"          : "coveralls/%org%/%bundle-name%/%branch%.svg"
      "scrutinizer"        : "scrutinizer/g/%org%/%bundle-name%/%branch%.svg"
      "gemnasium"          : "gemnasium/%org%/%bundle-name%.svg"
      "sensiolabs"         : "sensiolabs/i/%sensiolabs-id%.svg"
      "license"            : "badge/license-%license%-008ac6.svg"


"projects":

  "augustus-silencer-library":
    "codacy_id"  : "8e78cca68ce44baca387dedf2a1b2ab7"
    "styleci_id" : "68391716"

  "augustus-instantiator-library":
    "codacy_id"  : "b29a4ce174b8484596dcf01e070a04df"
    "styleci_id" : "69204701"

  "augustus-dumper-library":
    "codacy_id"  : "d6ee4c2711064ca3856ec4391e13d1ae"
    "styleci_id" : "68273462"

  "augustus-file-lock-library":
    "codacy_id"  : "7bf3d0721be64175822e846e3764c08d"
    "styleci_id" : "68176628"

  "augustus-file-object-library":
    "codacy_id"  : "932d2b59aa274ea89a02076c59dae75f"
    "styleci_id" : "68270148"

  "augustus-log-library":
    "codacy_id"  : "10e2534829264a5681dded0bd12603d5"
    "styleci_id" : "67976822"

  "augustus-deprecation-library":
    "codacy_id"  : "a89c3b43feef4c18a5518489b5d37655"
    "styleci_id" : "55302276"

  "augustus-exception-library":
    "codacy_id"  : "602c59fe0439485e9c55e0121f836355"
    "styleci_id" : "55028169"

  "augustus-polyfill-library":
    "codacy_id"  : "b9946ced91b04106be8e667882e00dac"
    "styleci_id" : "55291980"

  "augustus-primitive-library":
    "codacy_id"  : "75f0c51a5ec6409e9ad73212740d94ea"
    "styleci_id" : "44241976"

  "augustus-reflection-library":
    "codacy_id"  : "6ac4c5d15d864e02b6ca3b436d80b0e7"
    "styleci_id" : "54981750"

  "augustus-serializer-library":
    "codacy_id"  : "6c10311680294f57aa40bc14a1b835c1"
    "styleci_id" : "57453159"

  "augustus-utility-library":
    "codacy_id"  : "8f18dad5c54b46228ccbc0c5cadbf9a2"
    "styleci_id" : "55018312"

  "vermicious-console-io-library":
    "codacy_id" : "827d8cfe72bf42a99f72d0db1e3c8a8d"

  "vermicious-environment-library":
    "codacy_id" : "daa429c3c5724eb482d05c1a7de29e6a"

  "vermicious-deploy-library":
    "codacy_id" : "04f631561d6248fdb3158b5ea15a9201"

  "arthur-doctrine-exception-library":
    "codacy_id" : "048c20254782400daf17a22f167dbd7f"

  "arthur-doctrine-identity-library":
    "codacy_id" : "0d9fed93a0034f1ea981cf7fcd659fe2"

  "arthur-doctrine-entity-traits-library":
    "codacy_id" : "d2c1fd38afca4ea1809b74e2f2754d8b"

  "arthur-doctrine-library":
    "codacy_id" : "e234d28f7d3643c4aaa377ae92505f7a"

  "arthur-doctrine-uuid-library":
    "codacy_id" : "2891b03e2e814ae0b679d24c94a9581a"

  "arthur-doctrine-fixtures-bundle":
    "codacy_id" : "66683ef641b840beafba75f699373da8"

  "wonka-library":
    "codacy_id"  : "976d1226a233466183b2e76c09dc9582"
    "styleci_id" : "42804599"

  "wonka-bundle":
    "codacy_id"  : "f4e227b4b0614b809da4438bb5ee4ab0"
    "styleci_id" : "42904556"

  "teavee-object-cache-bundle":
    "codacy_id" : "dd26e12573f74e66826d7a9691c21b2c"

  "teavee-google-web-fonts-bundle":
    "codacy_id" : "2cf6a1710d824bcaabf060466d284342"

  "teavee-html-generator-bundle":
    "codacy_id" : "f16ee593decf4a29b7d261153c4449a4"

  "teavee-scribble-down-bundle":
    "codacy_id" : "fafb2c7b32ec4ad19e765df566a1951a"

  "teavee-image-magic-bundle":
    "codacy_id" : "aa9d93539cec4dc4806c135c15e79ade"

  "mantle-bundle":
    "codacy_id" : "4724225f607149f49944d7822416b939"

  "file-uploader-bundle":
    "codacy_id" : "cc224e4849ca4b889ff33cfcfa9a6164"
